### ISSUE TITLE
Adjust UI components styles

### ISSUE THREAD

**Issue by nicksp** [x-team/auto-ui#91]
The goal is to fine tune components styles to conform to designs. Also good opportunity to optimise markup in some places and remove dead code.

### Todo

- [x] Remove redundant markup
- [x] Remove dead code
- [x] Improve component styling
